//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangkokDrawResultHistory
    {
        public long ResultHistoryID { get; set; }
        public int ResultID { get; set; }
        public int DrawGameID { get; set; }
        public string ResultNumber { get; set; }
        public int ResultVersion { get; set; }
        public string ActionType { get; set; }
        public string PreviousResultNumber { get; set; }
        public string PreviousResultStatus { get; set; }
        public string NewResultStatus { get; set; }
        public Nullable<byte> PreviousRevealedDigitCount { get; set; }
        public byte NewRevealedDigitCount { get; set; }
        public string ActionReason { get; set; }
        public string ActionBy { get; set; }
        public System.DateTime ActionDateUTC { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
    
        public virtual BangkokDrawGame BangkokDrawGame { get; set; }
        public virtual BangkokDrawResult BangkokDrawResult { get; set; }
    }
}
