//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangkokDraw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangkokDraw()
        {
            this.BangkokDrawGames = new HashSet<BangkokDrawGame>();
            this.BangkokDrawPauseHistories = new HashSet<BangkokDrawPauseHistory>();
        }
    
        public int DrawID { get; set; }
        public string DrawCode { get; set; }
        public System.DateTime DrawDate { get; set; }
        public System.DateTime ScheduledStartUTC { get; set; }
        public string TimeZoneID { get; set; }
        public short CountdownMinutes { get; set; }
        public short RepeatEveryDays { get; set; }
        public Nullable<System.DateTime> NextDrawDate { get; set; }
        public string DrawStatus { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<System.DateTime> PublishedDateUTC { get; set; }
        public string PublishedBy { get; set; }
        public Nullable<System.DateTime> OriginalScheduledStartUTC { get; set; }
        public Nullable<System.DateTime> PostponedDateUTC { get; set; }
        public string PostponedBy { get; set; }
        public string PostponementReason { get; set; }
        public Nullable<System.DateTime> CancelledDateUTC { get; set; }
        public string CancelledBy { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<System.DateTime> CompletedDateUTC { get; set; }
        public string CompletedBy { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateUTC { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDateUTC { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> ActiveDrawKey { get; set; }
        public Nullable<System.DateTime> ActualStartUTC { get; set; }
        public Nullable<System.DateTime> ActualEndUTC { get; set; }
        public string DrawName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangkokDrawGame> BangkokDrawGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangkokDrawPauseHistory> BangkokDrawPauseHistories { get; set; }
    }
}
