//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangkokDrawGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangkokDrawGame()
        {
            this.BangkokDrawPauseHistories = new HashSet<BangkokDrawPauseHistory>();
            this.BangkokDrawResults = new HashSet<BangkokDrawResult>();
            this.BangkokDrawResultHistories = new HashSet<BangkokDrawResultHistory>();
        }
    
        public int DrawGameID { get; set; }
        public int DrawID { get; set; }
        public string GameCode { get; set; }
        public string GameName { get; set; }
        public string GameNameThai { get; set; }
        public byte DisplayOrder { get; set; }
        public byte DigitCount { get; set; }
        public int StartOffsetSeconds { get; set; }
        public short DigitRevealIntervalSeconds { get; set; }
        public decimal HostPickupSeconds { get; set; }
        public decimal BallFlightSeconds { get; set; }
        public decimal MachineRunSeconds { get; set; }
        public string GameStatus { get; set; }
        public Nullable<System.DateTime> ActualStartUTC { get; set; }
        public Nullable<System.DateTime> RevealStartedUTC { get; set; }
        public Nullable<System.DateTime> RevealCompletedUTC { get; set; }
        public Nullable<System.DateTime> CompletedDateUTC { get; set; }
        public bool IsActive { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateUTC { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<System.DateTime> ActualEndUTC { get; set; }
        public Nullable<System.DateTime> ScheduledStartUTC { get; set; }
    
        public virtual BangkokDraw BangkokDraw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangkokDrawPauseHistory> BangkokDrawPauseHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangkokDrawResult> BangkokDrawResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangkokDrawResultHistory> BangkokDrawResultHistories { get; set; }
    }
}
