//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangkokDrawPauseHistory
    {
        public int PauseHistoryID { get; set; }
        public int DrawID { get; set; }
        public Nullable<int> DrawGameID { get; set; }
        public System.DateTime PauseStartedUTC { get; set; }
        public string PauseReason { get; set; }
        public string PausedBy { get; set; }
        public Nullable<System.DateTime> ResumeDateUTC { get; set; }
        public string ResumeReason { get; set; }
        public string ResumedBy { get; set; }
        public Nullable<int> PauseDurationSeconds { get; set; }
        public Nullable<bool> IsResumed { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> OpenPauseKey { get; set; }
    
        public virtual BangkokDraw BangkokDraw { get; set; }
        public virtual BangkokDrawGame BangkokDrawGame { get; set; }
    }
}
