//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangkokDrawResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangkokDrawResult()
        {
            this.BangkokDrawResultHistories = new HashSet<BangkokDrawResultHistory>();
        }
    
        public int ResultID { get; set; }
        public int DrawGameID { get; set; }
        public string ResultNumber { get; set; }
        public string ResultStatus { get; set; }
        public string ResultSource { get; set; }
        public System.DateTime EnteredDateUTC { get; set; }
        public string EnteredBy { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<System.DateTime> ConfirmedDateUTC { get; set; }
        public string ConfirmedBy { get; set; }
        public bool IsLateEntry { get; set; }
        public Nullable<System.DateTime> ScheduledGameStartUTC { get; set; }
        public Nullable<int> EntryDelaySeconds { get; set; }
        public Nullable<System.DateTime> RevealStartedUTC { get; set; }
        public Nullable<System.DateTime> RevealCompletedUTC { get; set; }
        public byte RevealedDigitCount { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> LockedDateUTC { get; set; }
        public string LockedBy { get; set; }
        public int ResultVersion { get; set; }
        public bool IsCorrected { get; set; }
        public Nullable<System.DateTime> CorrectedDateUTC { get; set; }
        public string CorrectedBy { get; set; }
        public string CorrectionReason { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateUTC { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual BangkokDrawGame BangkokDrawGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangkokDrawResultHistory> BangkokDrawResultHistories { get; set; }
    }
}
