//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class return_orderEntities1 : DbContext
    {
        public return_orderEntities1()
            : base("name=return_orderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangkokDraw> BangkokDraws { get; set; }
        public virtual DbSet<BangkokDrawGame> BangkokDrawGames { get; set; }
        public virtual DbSet<BangkokDrawPauseHistory> BangkokDrawPauseHistories { get; set; }
        public virtual DbSet<BangkokDrawResult> BangkokDrawResults { get; set; }
        public virtual DbSet<BangkokDrawResultHistory> BangkokDrawResultHistories { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<Module_info> Module_info { get; set; }
        public virtual DbSet<page_info> page_info { get; set; }
        public virtual DbSet<user_permission> user_permission { get; set; }
        public virtual DbSet<userrole> userroles { get; set; }
        public virtual DbSet<View_GetPages> View_GetPages { get; set; }
        public virtual DbSet<View_GetUserPermissionModule> View_GetUserPermissionModule { get; set; }
        public virtual DbSet<View_GetUserPermissions> View_GetUserPermissions { get; set; }
    
        public virtual ObjectResult<Nullable<double>> GetPLAmount(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> add_club_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var add_club_idParameter = add_club_id.HasValue ?
                new ObjectParameter("add_club_id", add_club_id) :
                new ObjectParameter("add_club_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetPLAmount", from_dateParameter, to_dateParameter, add_club_idParameter);
        }
    
        public virtual ObjectResult<gettrialbalance_Result> gettrialbalance(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> add_club_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var add_club_idParameter = add_club_id.HasValue ?
                new ObjectParameter("add_club_id", add_club_id) :
                new ObjectParameter("add_club_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gettrialbalance_Result>("gettrialbalance", from_dateParameter, to_dateParameter, add_club_idParameter);
        }
    
        public virtual ObjectResult<GetBLAccounts_Result> GetBLAccounts(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> add_club_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var add_club_idParameter = add_club_id.HasValue ?
                new ObjectParameter("add_club_id", add_club_id) :
                new ObjectParameter("add_club_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBLAccounts_Result>("GetBLAccounts", from_dateParameter, to_dateParameter, add_club_idParameter);
        }
    
        public virtual ObjectResult<GetPLAccounts_Result> GetPLAccounts(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> add_club_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var add_club_idParameter = add_club_id.HasValue ?
                new ObjectParameter("add_club_id", add_club_id) :
                new ObjectParameter("add_club_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPLAccounts_Result>("GetPLAccounts", from_dateParameter, to_dateParameter, add_club_idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<GetFinalReport_Result> GetFinalReport(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> add_club_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var add_club_idParameter = add_club_id.HasValue ?
                new ObjectParameter("add_club_id", add_club_id) :
                new ObjectParameter("add_club_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFinalReport_Result>("GetFinalReport", from_dateParameter, to_dateParameter, add_club_idParameter);
        }
    
        public virtual ObjectResult<GetNumberInfo_Result> GetNumberInfo(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> game_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNumberInfo_Result>("GetNumberInfo", from_dateParameter, to_dateParameter, game_idParameter);
        }
    
        public virtual int Rpt_PubGetNumberInfo(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> game_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rpt_PubGetNumberInfo", from_dateParameter, to_dateParameter, game_idParameter);
        }
    
        public virtual ObjectResult<GetSearchNumberHistory_Result> GetSearchNumberHistory(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, string searchnumber, Nullable<int> game_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var searchnumberParameter = searchnumber != null ?
                new ObjectParameter("searchnumber", searchnumber) :
                new ObjectParameter("searchnumber", typeof(string));
    
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSearchNumberHistory_Result>("GetSearchNumberHistory", from_dateParameter, to_dateParameter, searchnumberParameter, game_idParameter);
        }
    
        public virtual ObjectResult<Rpt_GetResultNumberInfo_Result> Rpt_GetResultNumberInfo(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, string result_main_status, Nullable<int> login_id, Nullable<int> game_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var result_main_statusParameter = result_main_status != null ?
                new ObjectParameter("result_main_status", result_main_status) :
                new ObjectParameter("result_main_status", typeof(string));
    
            var login_idParameter = login_id.HasValue ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(int));
    
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_GetResultNumberInfo_Result>("Rpt_GetResultNumberInfo", from_dateParameter, to_dateParameter, result_main_statusParameter, login_idParameter, game_idParameter);
        }
    
        public virtual ObjectResult<Rpt_GetDayWiseResultNumberInfo_Result> Rpt_GetDayWiseResultNumberInfo(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> login_id, Nullable<int> game_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var login_idParameter = login_id.HasValue ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(int));
    
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_GetDayWiseResultNumberInfo_Result>("Rpt_GetDayWiseResultNumberInfo", from_dateParameter, to_dateParameter, login_idParameter, game_idParameter);
        }
    
        public virtual ObjectResult<Rpt_GetSingleDateResultDetail_Result> Rpt_GetSingleDateResultDetail(Nullable<System.DateTime> from_date, Nullable<int> login_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var login_idParameter = login_id.HasValue ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_GetSingleDateResultDetail_Result>("Rpt_GetSingleDateResultDetail", from_dateParameter, login_idParameter);
        }
    
        public virtual ObjectResult<Rpt_PubJodiGetNumberInfo_Result> Rpt_PubJodiGetNumberInfo(Nullable<int> game_id)
        {
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_PubJodiGetNumberInfo_Result>("Rpt_PubJodiGetNumberInfo", game_idParameter);
        }
    
        public virtual ObjectResult<Rpt_PubPanelGetNumberInfo_Result> Rpt_PubPanelGetNumberInfo(Nullable<int> game_id)
        {
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_PubPanelGetNumberInfo_Result>("Rpt_PubPanelGetNumberInfo", game_idParameter);
        }
    
        public virtual ObjectResult<Rpt_GetDayWiseSumaryReport_Result> Rpt_GetDayWiseSumaryReport(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<int> login_id, Nullable<int> game_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var login_idParameter = login_id.HasValue ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(int));
    
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_GetDayWiseSumaryReport_Result>("Rpt_GetDayWiseSumaryReport", from_dateParameter, to_dateParameter, login_idParameter, game_idParameter);
        }
    
        public virtual ObjectResult<Rpt_GetAssignGamesToUser_Result> Rpt_GetAssignGamesToUser(Nullable<int> login_id)
        {
            var login_idParameter = login_id.HasValue ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_GetAssignGamesToUser_Result>("Rpt_GetAssignGamesToUser", login_idParameter);
        }
    
        [DbFunction("return_orderEntities1", "fn_PubPanelGetNumberInfo")]
        public virtual IQueryable<fn_PubPanelGetNumberInfo_Result> fn_PubPanelGetNumberInfo(Nullable<int> game_id)
        {
            var game_idParameter = game_id.HasValue ?
                new ObjectParameter("game_id", game_id) :
                new ObjectParameter("game_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_PubPanelGetNumberInfo_Result>("[return_orderEntities1].[fn_PubPanelGetNumberInfo](@game_id)", game_idParameter);
        }
    
        [DbFunction("return_orderEntities1", "fn_SplitString")]
        public virtual IQueryable<string> fn_SplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[return_orderEntities1].[fn_SplitString](@string, @delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_AutoProcess_Result> sproc_BangkokDraw_AutoProcess()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_AutoProcess_Result>("sproc_BangkokDraw_AutoProcess");
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_Cancel_Result> sproc_BangkokDraw_Cancel(Nullable<int> drawID, string cancellationReason, string cancelledBy)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var cancellationReasonParameter = cancellationReason != null ?
                new ObjectParameter("CancellationReason", cancellationReason) :
                new ObjectParameter("CancellationReason", typeof(string));
    
            var cancelledByParameter = cancelledBy != null ?
                new ObjectParameter("CancelledBy", cancelledBy) :
                new ObjectParameter("CancelledBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_Cancel_Result>("sproc_BangkokDraw_Cancel", drawIDParameter, cancellationReasonParameter, cancelledByParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_Complete_Result> sproc_BangkokDraw_Complete(Nullable<int> drawID, string completedBy)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var completedByParameter = completedBy != null ?
                new ObjectParameter("CompletedBy", completedBy) :
                new ObjectParameter("CompletedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_Complete_Result>("sproc_BangkokDraw_Complete", drawIDParameter, completedByParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_ConfirmResult_Result> sproc_BangkokDraw_ConfirmResult(Nullable<int> resultID, string confirmedBy, string iPAddress, string userAgent)
        {
            var resultIDParameter = resultID.HasValue ?
                new ObjectParameter("ResultID", resultID) :
                new ObjectParameter("ResultID", typeof(int));
    
            var confirmedByParameter = confirmedBy != null ?
                new ObjectParameter("ConfirmedBy", confirmedBy) :
                new ObjectParameter("ConfirmedBy", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var userAgentParameter = userAgent != null ?
                new ObjectParameter("UserAgent", userAgent) :
                new ObjectParameter("UserAgent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_ConfirmResult_Result>("sproc_BangkokDraw_ConfirmResult", resultIDParameter, confirmedByParameter, iPAddressParameter, userAgentParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_Create_Result> sproc_BangkokDraw_Create(string drawCode, string drawName, Nullable<System.DateTime> drawDate, Nullable<System.DateTime> scheduledStartUTC, string timeZoneID, Nullable<short> countdownMinutes, Nullable<short> repeatEveryDays, Nullable<int> downStartOffsetSeconds, Nullable<int> firstStartOffsetSeconds, Nullable<short> digitRevealIntervalSeconds, string createdBy, string remarks, ObjectParameter newDrawID)
        {
            var drawCodeParameter = drawCode != null ?
                new ObjectParameter("DrawCode", drawCode) :
                new ObjectParameter("DrawCode", typeof(string));
    
            var drawNameParameter = drawName != null ?
                new ObjectParameter("DrawName", drawName) :
                new ObjectParameter("DrawName", typeof(string));
    
            var drawDateParameter = drawDate.HasValue ?
                new ObjectParameter("DrawDate", drawDate) :
                new ObjectParameter("DrawDate", typeof(System.DateTime));
    
            var scheduledStartUTCParameter = scheduledStartUTC.HasValue ?
                new ObjectParameter("ScheduledStartUTC", scheduledStartUTC) :
                new ObjectParameter("ScheduledStartUTC", typeof(System.DateTime));
    
            var timeZoneIDParameter = timeZoneID != null ?
                new ObjectParameter("TimeZoneID", timeZoneID) :
                new ObjectParameter("TimeZoneID", typeof(string));
    
            var countdownMinutesParameter = countdownMinutes.HasValue ?
                new ObjectParameter("CountdownMinutes", countdownMinutes) :
                new ObjectParameter("CountdownMinutes", typeof(short));
    
            var repeatEveryDaysParameter = repeatEveryDays.HasValue ?
                new ObjectParameter("RepeatEveryDays", repeatEveryDays) :
                new ObjectParameter("RepeatEveryDays", typeof(short));
    
            var downStartOffsetSecondsParameter = downStartOffsetSeconds.HasValue ?
                new ObjectParameter("DownStartOffsetSeconds", downStartOffsetSeconds) :
                new ObjectParameter("DownStartOffsetSeconds", typeof(int));
    
            var firstStartOffsetSecondsParameter = firstStartOffsetSeconds.HasValue ?
                new ObjectParameter("FirstStartOffsetSeconds", firstStartOffsetSeconds) :
                new ObjectParameter("FirstStartOffsetSeconds", typeof(int));
    
            var digitRevealIntervalSecondsParameter = digitRevealIntervalSeconds.HasValue ?
                new ObjectParameter("DigitRevealIntervalSeconds", digitRevealIntervalSeconds) :
                new ObjectParameter("DigitRevealIntervalSeconds", typeof(short));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_Create_Result>("sproc_BangkokDraw_Create", drawCodeParameter, drawNameParameter, drawDateParameter, scheduledStartUTCParameter, timeZoneIDParameter, countdownMinutesParameter, repeatEveryDaysParameter, downStartOffsetSecondsParameter, firstStartOffsetSecondsParameter, digitRevealIntervalSecondsParameter, createdByParameter, remarksParameter, newDrawID);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_Delete_Result> sproc_BangkokDraw_Delete(Nullable<int> drawID, string deletedBy)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var deletedByParameter = deletedBy != null ?
                new ObjectParameter("DeletedBy", deletedBy) :
                new ObjectParameter("DeletedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_Delete_Result>("sproc_BangkokDraw_Delete", drawIDParameter, deletedByParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_EnterResult_Result> sproc_BangkokDraw_EnterResult(Nullable<int> drawGameID, string resultNumber, string enteredBy, string resultSource, string remarks, string iPAddress, string userAgent)
        {
            var drawGameIDParameter = drawGameID.HasValue ?
                new ObjectParameter("DrawGameID", drawGameID) :
                new ObjectParameter("DrawGameID", typeof(int));
    
            var resultNumberParameter = resultNumber != null ?
                new ObjectParameter("ResultNumber", resultNumber) :
                new ObjectParameter("ResultNumber", typeof(string));
    
            var enteredByParameter = enteredBy != null ?
                new ObjectParameter("EnteredBy", enteredBy) :
                new ObjectParameter("EnteredBy", typeof(string));
    
            var resultSourceParameter = resultSource != null ?
                new ObjectParameter("ResultSource", resultSource) :
                new ObjectParameter("ResultSource", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var userAgentParameter = userAgent != null ?
                new ObjectParameter("UserAgent", userAgent) :
                new ObjectParameter("UserAgent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_EnterResult_Result>("sproc_BangkokDraw_EnterResult", drawGameIDParameter, resultNumberParameter, enteredByParameter, resultSourceParameter, remarksParameter, iPAddressParameter, userAgentParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_GetAdminControl_Result> sproc_BangkokDraw_GetAdminControl(Nullable<int> drawID, string drawCode)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var drawCodeParameter = drawCode != null ?
                new ObjectParameter("DrawCode", drawCode) :
                new ObjectParameter("DrawCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_GetAdminControl_Result>("sproc_BangkokDraw_GetAdminControl", drawIDParameter, drawCodeParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_GetList_Result> sproc_BangkokDraw_GetList(string drawStatus, string searchText, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var drawStatusParameter = drawStatus != null ?
                new ObjectParameter("DrawStatus", drawStatus) :
                new ObjectParameter("DrawStatus", typeof(string));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_GetList_Result>("sproc_BangkokDraw_GetList", drawStatusParameter, searchTextParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_GetLiveStatus_Result> sproc_BangkokDraw_GetLiveStatus(Nullable<int> drawID, string drawCode)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var drawCodeParameter = drawCode != null ?
                new ObjectParameter("DrawCode", drawCode) :
                new ObjectParameter("DrawCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_GetLiveStatus_Result>("sproc_BangkokDraw_GetLiveStatus", drawIDParameter, drawCodeParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_MarkReady_Result> sproc_BangkokDraw_MarkReady(Nullable<int> drawID, string modifiedBy)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var modifiedByParameter = modifiedBy != null ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_MarkReady_Result>("sproc_BangkokDraw_MarkReady", drawIDParameter, modifiedByParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_Pause_Result> sproc_BangkokDraw_Pause(Nullable<int> drawID, Nullable<int> drawGameID, string pauseReason, string pausedBy, string remarks)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var drawGameIDParameter = drawGameID.HasValue ?
                new ObjectParameter("DrawGameID", drawGameID) :
                new ObjectParameter("DrawGameID", typeof(int));
    
            var pauseReasonParameter = pauseReason != null ?
                new ObjectParameter("PauseReason", pauseReason) :
                new ObjectParameter("PauseReason", typeof(string));
    
            var pausedByParameter = pausedBy != null ?
                new ObjectParameter("PausedBy", pausedBy) :
                new ObjectParameter("PausedBy", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_Pause_Result>("sproc_BangkokDraw_Pause", drawIDParameter, drawGameIDParameter, pauseReasonParameter, pausedByParameter, remarksParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_Publish_Result> sproc_BangkokDraw_Publish(Nullable<int> drawID, string publishedBy)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var publishedByParameter = publishedBy != null ?
                new ObjectParameter("PublishedBy", publishedBy) :
                new ObjectParameter("PublishedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_Publish_Result>("sproc_BangkokDraw_Publish", drawIDParameter, publishedByParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_Resume_Result> sproc_BangkokDraw_Resume(Nullable<int> pauseHistoryID, string resumeReason, string resumedBy)
        {
            var pauseHistoryIDParameter = pauseHistoryID.HasValue ?
                new ObjectParameter("PauseHistoryID", pauseHistoryID) :
                new ObjectParameter("PauseHistoryID", typeof(int));
    
            var resumeReasonParameter = resumeReason != null ?
                new ObjectParameter("ResumeReason", resumeReason) :
                new ObjectParameter("ResumeReason", typeof(string));
    
            var resumedByParameter = resumedBy != null ?
                new ObjectParameter("ResumedBy", resumedBy) :
                new ObjectParameter("ResumedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_Resume_Result>("sproc_BangkokDraw_Resume", pauseHistoryIDParameter, resumeReasonParameter, resumedByParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_RevealNextDigit_Result> sproc_BangkokDraw_RevealNextDigit(Nullable<int> drawID, string revealedBy, string iPAddress, string userAgent)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var revealedByParameter = revealedBy != null ?
                new ObjectParameter("RevealedBy", revealedBy) :
                new ObjectParameter("RevealedBy", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var userAgentParameter = userAgent != null ?
                new ObjectParameter("UserAgent", userAgent) :
                new ObjectParameter("UserAgent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_RevealNextDigit_Result>("sproc_BangkokDraw_RevealNextDigit", drawIDParameter, revealedByParameter, iPAddressParameter, userAgentParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_SaveResult_Result> sproc_BangkokDraw_SaveResult(Nullable<int> drawID, string gameCode, string resultNumber, string enteredBy, string resultSource, string remarks, string iPAddress, string userAgent)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var gameCodeParameter = gameCode != null ?
                new ObjectParameter("GameCode", gameCode) :
                new ObjectParameter("GameCode", typeof(string));
    
            var resultNumberParameter = resultNumber != null ?
                new ObjectParameter("ResultNumber", resultNumber) :
                new ObjectParameter("ResultNumber", typeof(string));
    
            var enteredByParameter = enteredBy != null ?
                new ObjectParameter("EnteredBy", enteredBy) :
                new ObjectParameter("EnteredBy", typeof(string));
    
            var resultSourceParameter = resultSource != null ?
                new ObjectParameter("ResultSource", resultSource) :
                new ObjectParameter("ResultSource", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var userAgentParameter = userAgent != null ?
                new ObjectParameter("UserAgent", userAgent) :
                new ObjectParameter("UserAgent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_SaveResult_Result>("sproc_BangkokDraw_SaveResult", drawIDParameter, gameCodeParameter, resultNumberParameter, enteredByParameter, resultSourceParameter, remarksParameter, iPAddressParameter, userAgentParameter);
        }
    
        public virtual ObjectResult<sproc_BangkokDraw_StartBroadcast_Result> sproc_BangkokDraw_StartBroadcast(Nullable<int> drawID, string startedBy, Nullable<bool> allowScheduleOverride)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(int));
    
            var startedByParameter = startedBy != null ?
                new ObjectParameter("StartedBy", startedBy) :
                new ObjectParameter("StartedBy", typeof(string));
    
            var allowScheduleOverrideParameter = allowScheduleOverride.HasValue ?
                new ObjectParameter("AllowScheduleOverride", allowScheduleOverride) :
                new ObjectParameter("AllowScheduleOverride", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_BangkokDraw_StartBroadcast_Result>("sproc_BangkokDraw_StartBroadcast", drawIDParameter, startedByParameter, allowScheduleOverrideParameter);
        }
    }
}
