//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_info
    {
        public int page_id { get; set; }
        public string page_name { get; set; }
        public string page_icon { get; set; }
        public string page_url { get; set; }
        public int module_id { get; set; }
        public Nullable<decimal> orderby { get; set; }
    }
}
