//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permission
    {
        public int user_permission_id { get; set; }
        public int page_id { get; set; }
        public int module_id { get; set; }
        public Nullable<int> login_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> role_id { get; set; }
    }
}
