//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetUserPermissionModule
    {
        public int module_id { get; set; }
        public string module_name { get; set; }
        public string module_URL { get; set; }
        public string module_icon { get; set; }
        public Nullable<bool> module_nestted_list { get; set; }
        public Nullable<int> role_id { get; set; }
    }
}
